### ISSUE TITLE
远程访问时弹幕速度太快了，还不能调

### ISSUE THREAD

**Issue by nbsdba** [kaedei/dandanplay-libraryindex#15]

**Comment by kaedei** [comment]
远程访问的播放器是DPlayer，貌似它还没有提供调整速度的API？

**Comment by qmzmdqs** [comment]
直接改代码了，从 5s 改成 8s ，观感好了点
```css
.dplayer-danmaku .dplayer-danmaku-right.dplayer-danmaku-move {
    -webkit-animation: danmaku 8s linear;
    animation: danmaku 8s linear;
    -webkit-animation-play-state: paused;
    animation-play-state: paused;
}
```
