### ISSUE TITLE
网页播放体验简单优化

### ISSUE THREAD

**Issue by qmzmdqs** [kaedei/dandanplay-libraryindex#22]
对播放页，在 pc 和 移动端的效果做了一些简单的调整，移动端加个了 双击切换暂停播放 功能，给大家提供个参考

```css

/* 弹幕字体调小，仅在屏幕顶部 35% 显示 */
.dplayer-danmaku {
    font-size: 18px;
    height: 35%;
}

/* 弹幕移动速度调慢 5s -> 8s */
.dplayer-danmaku .dplayer-danmaku-right.dplayer-danmaku-move {
    -webkit-animation: danmaku 8s linear;
    animation: danmaku 8s linear;
    -webkit-animation-play-state: paused;
    animation-play-state: paused;
}

/* mobile */

/* 控制条 mask 高度调小，避免影响双击切换暂停播放 */
.dplayer-mobile .dplayer-controller-mask {
    height: 60px;
}

/* 弹幕字体调小 */
.dplayer-mobile .dplayer-danmaku {
    font-size: 13px;
}
.dplayer.dplayer-arrow.dplayer-mobile .dplayer-danmaku {
    font-size: 13px;
}
```

```javascript
// 移动端双击切换暂停播放
let lastClickTime = 0
let lastPlayerPausedStatus = true
$(".dplayer-video").click(function () {
	let now = Date.now()
	let interval = now - lastClickTime

	if (interval < 300) {
		if (lastPlayerPausedStatus === dp.paused) {
			console.log('player double click toggle pause')
			dp.toggle()
		}
	}

	lastClickTime = now
	lastPlayerPausedStatus = dp.paused
});
```
